---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cities":
    get:
      summary: list cities
      responses:
        '200':
          description: successful
    post:
      summary: create city
      responses:
        '200':
          description: successful
  "/cities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show city
      responses:
        '200':
          description: successful
    put:
      summary: update city
      responses:
        '200':
          description: successful
    delete:
      summary: delete city
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  contentType: application/json
  headers:
    contentType:
      description: content type
      schema:
        type: string
